export const UPDATE_CURRENT_GUESS = "UPDATE_CURRENT_GUESS";
export const SET_CURRENT_GUESS_COUNTER = "SET_CURRENT_GUESS_COUNTER";
export const SET_GAME_OVER = "SET_GAME_OVER";
export const INITIALISE_BOARD = "INITIALISE_BOARD";
